# generated by datamodel-codegen:
#   filename:  analysis_openapi.json
#   timestamp: 2025-05-29T18:59:22+00:00

from __future__ import annotations

from typing import List, Optional, Union

from pydantic import BaseModel, Field


class FileStatDTO(BaseModel):
    file_id: int = Field(..., title='File Id')
    word_count: int = Field(..., title='Word Count')
    char_count: int = Field(..., title='Char Count')
    is_unique: bool = Field(..., title='Is Unique')
    wordcloud_location: str = Field(..., title='Wordcloud Location')


class ValidationError(BaseModel):
    loc: List[Union[str, int]] = Field(..., title='Location')
    msg: str = Field(..., title='Message')
    type: str = Field(..., title='Error Type')


class HTTPValidationError(BaseModel):
    detail: Optional[List[ValidationError]] = Field(None, title='Detail')
