# generated by datamodel-codegen:
#   filename:  files_openapi.json
#   timestamp: 2025-05-29T19:00:58+00:00

from __future__ import annotations

from typing import List, Optional, Union

from pydantic import BaseModel, Field


class BodyUploadFileFilesPost(BaseModel):
    file: bytes = Field(..., title='File')


class FileContentResponse(BaseModel):
    file_text: str = Field(..., title='File Text')


class UploadResponse(BaseModel):
    file_id: int = Field(..., title='File Id')


class ValidationError(BaseModel):
    loc: List[Union[str, int]] = Field(..., title='Location')
    msg: str = Field(..., title='Message')
    type: str = Field(..., title='Error Type')


class HTTPValidationError(BaseModel):
    detail: Optional[List[ValidationError]] = Field(None, title='Detail')
