database:
  host: store-db
  port: 5432
  user: "${POSTGRES_USER}"
  password: "${POSTGRES_PASSWORD}"
  name: store-db
  database_system: postgresql
  driver: asyncpg
minio:
  host: minio
  port: 9000
  secure: false
  access_key: "${MINIO_ACCESS_KEY}"
  secret_key: "${MINIO_SECRET_KEY}"
  bucket_name: "${MINIO_BUCKET}"